### ISSUE TITLE
Next components creation

### ISSUE THREAD

**Issue by jitsedesmet** [SELab-2/OSOC-6#184]
This issue is used to track the creation of components. The [Figma mock-up](https://www.figma.com/file/pvrjnLp3X2SUdeeXnbZD3W/OSOC?node-id=0%3A1) can be a great help in this task.

## Other
- [x] Navigation bar ~ lvrossem #198
- [x] Project list ~ lvrossem #211 
- [x] Create new project ~ lvrossem #216 
- [ ] Warning toast for errors
- [ ] Info bubble (maybe a lib comp, write it here)
- [x] Registration page ~ andpuydt #327 
- [x] Logout ~ ruvmello
- [ ] Aanpassen edition ~ lvrossem #402 
- [x] Reset password ~ruvmello
- [x] Forgot/reset password ~KasperDemeyere #409
- [ ] No permission warning screen
## Students 
- [x] Student list ~ andpuydt  #293 
- [x] Filters : Roles, Student coach/alumni, ... ~ jitsedesmet #328
- [x] Filters : yes, maybe, no ~ jitsedesmet #328
- [x] Student overview ~andpuydt #317 
- [x] Colored line for quick impression ~ jitsedesmet - andpuydt #315
- [x] Status filter ~ andpuydt #407
- [x] Remove a student
## Users
- [x] User component ~ ruvmello #289 
- [x] List of user components ~ ruvmello #289 
- [x] Send token to new user - communication template
- [x] Invite new user
## Projects
- [x] Overview projectinfo ~ jitsedesmet #304 
- [ ] Expertise needed for project
- [ ] Roles needed for project  
- [ ] Project list for assignment ~thvmulle
- [ ] Project view for assignments
## User profile
- [x] User overview ~ ruvmello #262 
- [x] Edit password ~ ruvmello
## Communication
- [x] Communication creation @jitsedesmet #430
- [x] Communication info ~ @jitsedesmet  #399 
- [x] communication template info ~ @jitsedesmet #390
- [x] communication template creation ~ @jitsedesmet #386
- [x] communication template list @jitsedesmet #437
- [x] communication list ~ @jitsedesmet #434
- [x] edit communicationTemplate ~ @jitsedesmet #445
## SkillType
- [x] create skilltype ~ @jitsedesmet  #442
- [x] edit skillType ~ @jitsedesmet #441

**Comment by KasperDemeyere** [comment]
We are done with the components.
