### ISSUE TITLE
Add data-testids to components

### ISSUE THREAD

**Issue by thvmulle** [SELab-2/OSOC-6#332]
Each component should have a `data-testid`, these are used for testing whether a component is present on a page.
The `data-testid`s should be added in the outer `<div>` elements of the components.
The naming conventions we will use are:

1. the id should have the same name as the component
2. every capital letter will be replace by a - and the lowercase letter

ex. ProjectList:
```Typescript
return (
    <div data-testid="project-list">
        ...
    </div>
);
```

Components that need to be refactored:

- [ ] [login-form](../blob/development/frontend/src/components/loginForm.tsx)
- [ ] [manage-user-component](../blob/development/frontend/src/components/manageUserComponent.tsx)
- [x] [new-project-button](../blob/development/frontend/src/components/newProjectButton.tsx) (#331)
- [ ] [profile-overview](../blob/development/frontend/src/components/profileOverview.tsx)
- [ ] [project-info](../blob/development/frontend/src/components/projectInfo.tsx)
- [x] [project-list](../blob/development/frontend/src/components/projectList.tsx) (#331)
- [ ] [suggestion-count](../blob/development/frontend/src/components/suggestionCount.tsx)
- [x] [nav-bar](../blob/development/frontend/src/components/navBar.tsx) (#331)
